# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Sum_C <- function(x) {
    .Call(`_BoostMLR_Sum_C`, x)
}

Sum_C_NA <- function(x) {
    .Call(`_BoostMLR_Sum_C_NA`, x)
}

Sum_numericVectors <- function(x, y) {
    .Call(`_BoostMLR_Sum_numericVectors`, x, y)
}

length_C_NA <- function(x) {
    .Call(`_BoostMLR_length_C_NA`, x)
}

length_integer_C_NA <- function(x) {
    .Call(`_BoostMLR_length_integer_C_NA`, x)
}

length_character_C_NA <- function(x) {
    .Call(`_BoostMLR_length_character_C_NA`, x)
}

Mean_C <- function(x) {
    .Call(`_BoostMLR_Mean_C`, x)
}

Mean_C_NA <- function(x) {
    .Call(`_BoostMLR_Mean_C_NA`, x)
}

Which_C <- function(x, x_set) {
    .Call(`_BoostMLR_Which_C`, x, x_set)
}

Which_C_NA <- function(x, x_set) {
    .Call(`_BoostMLR_Which_C_NA`, x, x_set)
}

Which_direction_C_NA <- function(x, x_set, direction) {
    .Call(`_BoostMLR_Which_direction_C_NA`, x, x_set, direction)
}

Which_integer_C <- function(x, x_set) {
    .Call(`_BoostMLR_Which_integer_C`, x, x_set)
}

Which_integer_C_NA <- function(x, x_set) {
    .Call(`_BoostMLR_Which_integer_C_NA`, x, x_set)
}

create_integer_vector <- function(start_point, end_point) {
    .Call(`_BoostMLR_create_integer_vector`, start_point, end_point)
}

Which_Min_C <- function(x) {
    .Call(`_BoostMLR_Which_Min_C`, x)
}

Which_Min_C_NA <- function(x) {
    .Call(`_BoostMLR_Which_Min_C_NA`, x)
}

Which_Min_C_NA_NRA <- function(x) {
    .Call(`_BoostMLR_Which_Min_C_NA_NRA`, x)
}

Which_Max_C <- function(x) {
    .Call(`_BoostMLR_Which_Max_C`, x)
}

Which_Max_C_NA <- function(x) {
    .Call(`_BoostMLR_Which_Max_C_NA`, x)
}

Which_Max_C_NA_NRA <- function(x) {
    .Call(`_BoostMLR_Which_Max_C_NA_NRA`, x)
}

StdVar_C <- function(MyMat) {
    .Call(`_BoostMLR_StdVar_C`, MyMat)
}

StdVar_C_NA_Supply_MeanSE <- function(MyMat, x_Mean, x_Std_Error) {
    .Call(`_BoostMLR_StdVar_C_NA_Supply_MeanSE`, MyMat, x_Mean, x_Std_Error)
}

StdVar_C_NA <- function(MyMat) {
    .Call(`_BoostMLR_StdVar_C_NA`, MyMat)
}

Match_C <- function(x_subset, x_set) {
    .Call(`_BoostMLR_Match_C`, x_subset, x_set)
}

Match_C_NA <- function(x_subset, x_set) {
    .Call(`_BoostMLR_Match_C_NA`, x_subset, x_set)
}

Approx_Match_C <- function(x, y) {
    .Call(`_BoostMLR_Approx_Match_C`, x, y)
}

Approx_Match_C_NA <- function(x, y) {
    .Call(`_BoostMLR_Approx_Match_C_NA`, x, y)
}

Diag_Matrix_C <- function(x) {
    .Call(`_BoostMLR_Diag_Matrix_C`, x)
}

Matrix_Sum_C <- function(x, y) {
    .Call(`_BoostMLR_Matrix_Sum_C`, x, y)
}

Matrix_Sum_C_NA <- function(x, y) {
    .Call(`_BoostMLR_Matrix_Sum_C_NA`, x, y)
}

l2Dist_Vector_C <- function(x1, x2, ID) {
    .Call(`_BoostMLR_l2Dist_Vector_C`, x1, x2, ID)
}

l2Dist_Vector_C_NA <- function(x1, x2, ID) {
    .Call(`_BoostMLR_l2Dist_Vector_C_NA`, x1, x2, ID)
}

set_seed <- function(seed) {
    invisible(.Call(`_BoostMLR_set_seed`, seed))
}

randomShuffle <- function(x, size, setting_seed, seed_value, replace, p) {
    .Call(`_BoostMLR_randomShuffle`, x, size, setting_seed, seed_value, replace, p)
}

int_randomShuffle <- function(x, size, setting_seed, seed_value, replace, p) {
    .Call(`_BoostMLR_int_randomShuffle`, x, size, setting_seed, seed_value, replace, p)
}

single_integer_randomShuffle <- function(x, size, setting_seed, seed_value, replace, p) {
    .Call(`_BoostMLR_single_integer_randomShuffle`, x, size, setting_seed, seed_value, replace, p)
}

Reverse_Ordering <- function(a) {
    .Call(`_BoostMLR_Reverse_Ordering`, a)
}

RemoveNA <- function(x) {
    .Call(`_BoostMLR_RemoveNA`, x)
}

RemoveNA_Integer <- function(x) {
    .Call(`_BoostMLR_RemoveNA_Integer`, x)
}

RemoveNA_Character <- function(x) {
    .Call(`_BoostMLR_RemoveNA_Character`, x)
}

Max_C_NA <- function(x) {
    .Call(`_BoostMLR_Max_C_NA`, x)
}

Max_upper_limit_C_NA <- function(x, x_upper_limit) {
    .Call(`_BoostMLR_Max_upper_limit_C_NA`, x, x_upper_limit)
}

Min_C_NA <- function(x) {
    .Call(`_BoostMLR_Min_C_NA`, x)
}

stl_sort <- function(x) {
    .Call(`_BoostMLR_stl_sort`, x)
}

stl_sort_NA <- function(x) {
    .Call(`_BoostMLR_stl_sort_NA`, x)
}

stl_sort_reverse <- function(x) {
    .Call(`_BoostMLR_stl_sort_reverse`, x)
}

stl_sort_reverse_NA <- function(x) {
    .Call(`_BoostMLR_stl_sort_reverse_NA`, x)
}

unique_C <- function(x) {
    .Call(`_BoostMLR_unique_C`, x)
}

unique_C_NA <- function(x) {
    .Call(`_BoostMLR_unique_C_NA`, x)
}

unique_character_C_NA <- function(x) {
    .Call(`_BoostMLR_unique_character_C_NA`, x)
}

unique_integer_C <- function(x) {
    .Call(`_BoostMLR_unique_integer_C`, x)
}

unique_integer_C_NA <- function(x) {
    .Call(`_BoostMLR_unique_integer_C_NA`, x)
}

cumulative_integer_sum <- function(x) {
    .Call(`_BoostMLR_cumulative_integer_sum`, x)
}

sort_unique_C <- function(x) {
    .Call(`_BoostMLR_sort_unique_C`, x)
}

sort_unique_C_NA <- function(x) {
    .Call(`_BoostMLR_sort_unique_C_NA`, x)
}

sort_unique_integer_C <- function(x) {
    .Call(`_BoostMLR_sort_unique_integer_C`, x)
}

sort_unique_integer_C_NA <- function(x) {
    .Call(`_BoostMLR_sort_unique_integer_C_NA`, x)
}

pmax_two_integers <- function(x1, x2) {
    .Call(`_BoostMLR_pmax_two_integers`, x1, x2)
}

Which_Max_Matrix <- function(x) {
    .Call(`_BoostMLR_Which_Max_Matrix`, x)
}

Which_Max_Matrix_NA <- function(x) {
    .Call(`_BoostMLR_Which_Max_Matrix_NA`, x)
}

Which_Max_Matrix_NA_NRA <- function(x) {
    .Call(`_BoostMLR_Which_Max_Matrix_NA_NRA`, x)
}

Which_Min_Matrix_NA <- function(x) {
    .Call(`_BoostMLR_Which_Min_Matrix_NA`, x)
}

Which_Min_Matrix_NA_NRA <- function(x) {
    .Call(`_BoostMLR_Which_Min_Matrix_NA_NRA`, x)
}

rowSums_C <- function(x) {
    .Call(`_BoostMLR_rowSums_C`, x)
}

rowSums_C_NA <- function(x) {
    .Call(`_BoostMLR_rowSums_C_NA`, x)
}

isNA <- function(x) {
    .Call(`_BoostMLR_isNA`, x)
}

isNA_Numeric <- function(x) {
    .Call(`_BoostMLR_isNA_Numeric`, x)
}

any_function <- function(x) {
    .Call(`_BoostMLR_any_function`, x)
}

all_function <- function(x) {
    .Call(`_BoostMLR_all_function`, x)
}

Rho_Inv_C <- function(Rho_Value, N_Value) {
    .Call(`_BoostMLR_Rho_Inv_C`, Rho_Value, N_Value)
}

MatrixInversion_Equicorrelation_C <- function(N_Value, phi, rho) {
    .Call(`_BoostMLR_MatrixInversion_Equicorrelation_C`, N_Value, phi, rho)
}

Matrix_Vector_Multiplication_C <- function(y, x) {
    .Call(`_BoostMLR_Matrix_Vector_Multiplication_C`, y, x)
}

Matrix_Vector_Multiplication_C_naObs <- function(y, x) {
    .Call(`_BoostMLR_Matrix_Vector_Multiplication_C_naObs`, y, x)
}

interaction_two_integer_sets <- function(x, y) {
    .Call(`_BoostMLR_interaction_two_integer_sets`, x, y)
}

Matrix_Multiplication_Arma_C <- function(x, y) {
    .Call(`_BoostMLR_Matrix_Multiplication_Arma_C`, x, y)
}

Matrix_Sum_Arma_C_NA <- function(x, y) {
    .Call(`_BoostMLR_Matrix_Sum_Arma_C_NA`, x, y)
}

all_equal <- function(x, y) {
    .Call(`_BoostMLR_all_equal`, x, y)
}

convert_double_string <- function(x) {
    .Call(`_BoostMLR_convert_double_string`, x)
}

round_NumVector <- function(x, d) {
    .Call(`_BoostMLR_round_NumVector`, x, d)
}

round_double <- function(x, d) {
    .Call(`_BoostMLR_round_double`, x, d)
}

Convert_DF_into_NumMat <- function(x) {
    .Call(`_BoostMLR_Convert_DF_into_NumMat`, x)
}

DiagonalMatrix_C <- function(Dimension, x) {
    .Call(`_BoostMLR_DiagonalMatrix_C`, Dimension, x)
}

MatrixInversion_R <- function(x) {
    .Call(`_BoostMLR_MatrixInversion_R`, x)
}

MatrixInversion_C <- function(x) {
    .Call(`_BoostMLR_MatrixInversion_C`, x)
}

Subsetting_Dataframe <- function(x, Index) {
    .Call(`_BoostMLR_Subsetting_Dataframe`, x, Index)
}

create_index_logical_vector <- function(x) {
    .Call(`_BoostMLR_create_index_logical_vector`, x)
}

create_variable_by_substitution <- function(x, x_sub) {
    .Call(`_BoostMLR_create_variable_by_substitution`, x, x_sub)
}

create_sequence <- function(min_value, max_value, by_amount) {
    .Call(`_BoostMLR_create_sequence`, min_value, max_value, by_amount)
}

fit_component_gls <- function(x, y, v, add_intercept) {
    .Call(`_BoostMLR_fit_component_gls`, x, y, v, add_intercept)
}

fit_component_gls_line_search <- function(x, y, v) {
    .Call(`_BoostMLR_fit_component_gls_line_search`, x, y, v)
}

sq_residual <- function(x, y, beta, add_intercept) {
    .Call(`_BoostMLR_sq_residual`, x, y, beta, add_intercept)
}

extract_linear_pred <- function(N, Index, x, beta, add_intercept) {
    .Call(`_BoostMLR_extract_linear_pred`, N, Index, x, beta, add_intercept)
}

extract_base_learner <- function(x, beta, add_intercept, No_coef) {
    .Call(`_BoostMLR_extract_base_learner`, x, beta, add_intercept, No_coef)
}

extract_mu <- function(x, link) {
    .Call(`_BoostMLR_extract_mu`, x, link)
}

DataProcessing_C <- function(Org_x, Org_y, id, tm, id_x, tm_x, unq_id, x_miss, trace, y_summary_supply, y_mean_supply, y_std_error_supply) {
    .Call(`_BoostMLR_DataProcessing_C`, Org_x, Org_y, id, tm, id_x, tm_x, unq_id, x_miss, trace, y_summary_supply, y_mean_supply, y_std_error_supply)
}

BoostMLR_C <- function(Org_x, Org_y, id, tm, x, y, id_x, tm_x, x_Mean, x_Std_Error, y_Mean, y_Std_Error, y_scale_summary, intercept, time_map, n, K, L, H, G, Dk, ni, ni_x, N, N_x, unq_id, unq_tm, unq_tm_x, unq_x, id_index, id_index_x, Bt, Bt_x, Bx, Bx_Scale, Bx_Scale_const, Time_Add_New, Time_Unmatch, nu, M, Mod_Grad, UseRaw, Lambda_Ridge_Vec, Ridge_Penalty, Shrink, lower_perc, upper_perc, Lambda_Scale, NLambda, VarFlag, rho, phi, setting_seed, seed_value, sq_residual_select, update_all_comp, comp_x, comp_y, Verbose, Trace) {
    .Call(`_BoostMLR_BoostMLR_C`, Org_x, Org_y, id, tm, x, y, id_x, tm_x, x_Mean, x_Std_Error, y_Mean, y_Std_Error, y_scale_summary, intercept, time_map, n, K, L, H, G, Dk, ni, ni_x, N, N_x, unq_id, unq_tm, unq_tm_x, unq_x, id_index, id_index_x, Bt, Bt_x, Bx, Bx_Scale, Bx_Scale_const, Time_Add_New, Time_Unmatch, nu, M, Mod_Grad, UseRaw, Lambda_Ridge_Vec, Ridge_Penalty, Shrink, lower_perc, upper_perc, Lambda_Scale, NLambda, VarFlag, rho, phi, setting_seed, seed_value, sq_residual_select, update_all_comp, comp_x, comp_y, Verbose, Trace)
}

update_BoostMLR_C <- function(Org_x, Org_y, id, tm, x, y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, K, L, H, Dk, ni, N, unq_id, unq_tm, unq_x, id_index, tm_index, x_index, Bt, Bx, Bt_H, Bx_K, Bxt, Bx_Scale, nu, M, M_New, UseRaw, Shrink, Ridge_Penalty, Lambda_Ridge_Vec, Lambda_Scale, NLambda, lower_perc, upper_perc, Lambda_List, mu, mu_List, mu_zero, Vec_zero, Error_Rate, Variable_Select, Response_Select, Beta_Hat_List, Sum_Beta_Hat_List, Beta, Beta_Hat_List_Iter, lower_Beta_Hat_Noise, upper_Beta_Hat_Noise, List_Trace_Bxt_gm, Mod_Grad, VarFlag, phi, rho, Phi, Rho, setting_seed, seed_value, Verbose) {
    .Call(`_BoostMLR_update_BoostMLR_C`, Org_x, Org_y, id, tm, x, y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, K, L, H, Dk, ni, N, unq_id, unq_tm, unq_x, id_index, tm_index, x_index, Bt, Bx, Bt_H, Bx_K, Bxt, Bx_Scale, nu, M, M_New, UseRaw, Shrink, Ridge_Penalty, Lambda_Ridge_Vec, Lambda_Scale, NLambda, lower_perc, upper_perc, Lambda_List, mu, mu_List, mu_zero, Vec_zero, Error_Rate, Variable_Select, Response_Select, Beta_Hat_List, Sum_Beta_Hat_List, Beta, Beta_Hat_List_Iter, lower_Beta_Hat_Noise, upper_Beta_Hat_Noise, List_Trace_Bxt_gm, Mod_Grad, VarFlag, phi, rho, Phi, Rho, setting_seed, seed_value, Verbose)
}

predict_BoostMLR_C <- function(Org_x, tm, id, Org_y, id_x, tm_x, x_Mean, x_Std_Error, y_Mean, y_Std_Error, intercept, y_scale_summary, time_map, K, L, H, G, Dk, unq_id, unq_tm, unq_tm_x, unq_x, Bt, Bt_x, Bx, UseRaw, Time_Add_New, Time_Unmatch, Beta, Beta_Hat_List, testFlag, M, nu, Time_Varying, vimpFlag, vimpFlag_Coef, eps, setting_seed, seed_value) {
    .Call(`_BoostMLR_predict_BoostMLR_C`, Org_x, tm, id, Org_y, id_x, tm_x, x_Mean, x_Std_Error, y_Mean, y_Std_Error, intercept, y_scale_summary, time_map, K, L, H, G, Dk, unq_id, unq_tm, unq_tm_x, unq_x, Bt, Bt_x, Bx, UseRaw, Time_Add_New, Time_Unmatch, Beta, Beta_Hat_List, testFlag, M, nu, Time_Varying, vimpFlag, vimpFlag_Coef, eps, setting_seed, seed_value)
}

vimp_BoostMLR_C <- function(Org_x, Org_y, tm, id, id_x, tm_x, x_Mean, x_Std_Error, y_Mean, y_Std_Error, intercept, y_scale_summary, n, ni, ni_x, N, N_x, L, K, p, H, G, Dk, n_unq_tm, n_unq_tm_x, UseRaw, id_index, id_index_x, tm_index, tm_index_x, unq_x_New, Index_Bt, Index_Bt_x, vimp_set, joint, Bt, Bt_x, Bt_H, Bt_G, Bx, Bxt, Bx_K, time_map, Beta_Hat_List, Mopt, nu, rmse, Time_Varying, Vec_zero, mu_zero_vec, setting_seed, seed_value) {
    .Call(`_BoostMLR_vimp_BoostMLR_C`, Org_x, Org_y, tm, id, id_x, tm_x, x_Mean, x_Std_Error, y_Mean, y_Std_Error, intercept, y_scale_summary, n, ni, ni_x, N, N_x, L, K, p, H, G, Dk, n_unq_tm, n_unq_tm_x, UseRaw, id_index, id_index_x, tm_index, tm_index_x, unq_x_New, Index_Bt, Index_Bt_x, vimp_set, joint, Bt, Bt_x, Bt_H, Bt_G, Bx, Bxt, Bx_K, time_map, Beta_Hat_List, Mopt, nu, rmse, Time_Varying, Vec_zero, mu_zero_vec, setting_seed, seed_value)
}

